CREATE TABLE
    IF NOT EXISTS tags (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name STRING,
        translated_name STRING,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );